### ISSUE TITLE
Support for alias ?

### ISSUE THREAD

**Issue by arnaudlimbourg** [segment-integrations/integration-amplitude#37]
Hello,

I was wondering if it would be possible for the ``alias`` call to be supported. Right now we have to make a call to identify adding the ``anonymous_id``.

Since ``alias`` is made for that it looks like it would make sense for it to be supported.

Thanks,

**Comment by hankim813** [comment]
@arnaudlimbourg Hey there -- I don't think Amplitude as an endpoint for alias. Sometimes if the integration itself doesn't expose an endpoint or an API that can map to our `.alias()` api, then we do not add support for it for that tool.

With that said, are you having trouble tying anonymous users to identified users? That sounds more like implementation issue of your tracking code.  I'd contact our support team for help on this since I do not believe Amplitude users have an issue since Amplitude should be able to alias on their own anonymous activity to their corresponding identified profile. This can get tricky if you are making calls from both server + client side for anonymous/identified data. More context around how you make `.identify()` calls can be helpful to know

**Comment by arnaudlimbourg** [comment]
Hi there,

I just pushed to prod the ``identify`` call with the ``anonymous_id`` parameter like the documentation states. Because I already do an ``alias`` call it would be nice not to have an extra call to ``identify`` but it's not the end of the world.

As you mention I do have issues because of server + client calls, it is for an invitation flow so the first calls are from server then there are both but if I don't tell amplitude, there is not way for it to know :)

**Comment by hankim813** [comment]
@arnaudlimbourg gotcha -- yeah so looking at the code for `.identify()` here: https://github.com/segment-integrations/integration-amplitude/blob/ddf8991a7ec9af4d460b21e79c5d48a1ebe88840/lib/mapper.js#L107

looks like we only fallback to anonymousId for non-mobile calls that would not have the `context.device.id` and the `userId` is just mapped to the top level `userId` as seen here: https://github.com/segment-integrations/integration-amplitude/blob/ddf8991a7ec9af4d460b21e79c5d48a1ebe88840/lib/mapper.js#L121

Yeah my recommendation would be to let Amplitude's JS library handle the anonymous user <> identified user connection. If I recall correctly, Amplitude will set its own client side anonymousId. So you should just call `.track()` to record events like "Invitation Sent" and Amplitude will create an anonymous profile in their database and attach it to that anonymous track event. Once the user signs up, you can call `.identify()` on the client side just to send your `userId`. This will allow Amplitude to merge its own `anonymousId` with your `userId`, effectively showing you the full conversion flow. If you want to send more sensitive user data from your server side, you can always make that server side `.identify()` call _after_ the client side call. That way you won't have dupe profiles in Amplitude and would not need to worry about parsing Segment's anonymousId from your browser's cookie, pass it to your server and send it to Amplitude.. Let me know if that makes sense!

**Comment by arnaudlimbourg** [comment]
It does make sense but I cannot send the ``Invitation Sent`` from the client. When that event occurs it is sent by an active (identified) user but I attach the event to the receiver, not the sender. If I were to make a call client side it would be attached to the sender.

On the server side I generate my own ``anonymousId`` which I use for the ``identify``call so my second call can use both ``anonymousId`` and ``userId`` which I create when the user acceptd the invitation.

I think this works, I need to check :)

**Comment by hankim813** [comment]
@arnaudlimbourg can you show me what this call looks like in your code?

> On the server side I generate my own anonymousId which I use for the `identify` call

**Comment by arnaudlimbourg** [comment]
I use the python library and the call is something like

```
    traits = {
        'email': user.email,
        'firstName': user.first_name,
        'lastName': user.last_name,
        'is_staff': user.is_staff,
    }
        analytics.identify(user.id, traits, anonymous_id=anonymous_id)
```

In the code that runs the alias I do

```
        alias(invite_key, user.id)

        # Amplitude needs to be told the anonymousId to match accounts
        # so we have a specific call, it works like alias which the amplitude
        # integration doesn't support apparently
        identify(user, anonymous_id=invite_key)

```

**Comment by hankim813** [comment]
@arnaudlimbourg hmm I'm not a python guru but it looks like you're passing `anonymous_id` as a `context` field? Or is that getting set to the top level field? If the latter, then it would be set as the `device_id` field in Amplitude. That will not be mapped anywhere in the integration.

But I'm confused, that first `.identify()` call has the user.id though. I thought they were anonymous?

Right now `.alias()` will have no effect for amplitude since it is not supported.

**Comment by arnaudlimbourg** [comment]
@hankim813 let me try to explain the whole flow so that it makes more sense (I should have started with that!). The `anonymous_id` is passed a keyword argument to the method.

User A sends an invitation to user B (whom I don't know), an invitation with a uuid is created, I `track` an event for an anonymous user which has this invitation uuid as the user id.

```
identify(invitation_uuid)  # identify an anonymous user
track(invitation_uuid, 'Invitation Sent')  # track an event for this anonymous user so customer.io can send the email
```

Later User B accepts this invitation. At this point a user created so I know who this is. This is when I call the `alias` method to tell segment that the invited user who was not known is now known.

```
        identify(user, anonymous_id=invite_key) 
        # Tell  segment this new user is actually one that already exists
        alias(invite_key, user.id)
```

I hope that makes more sense.

As far as I can see Amplitude is able to merge the two (they have the same `amplitudeid`) but customer.io creates two profiles (sigh)

**Comment by hankim813** [comment]
> User A sends an invitation to user B (whom I don't know), an invitation with a uuid is created, I track an event for an anonymous user which has this invitation uuid as the user id.

It's always a bad idea to call `.identify()` where the `userId = anonymousId` because your downstream tools will think that is an identified user and create a new profile. So this current flow effectively creates 2x users per person. This might work for amplitude but bad implementation which will be a headache to clean up later.

You should call identify but set the anonymousId as the invitation uuid. Later when you call identify for user B, you should also send that same invitation uuid as the anonymousId for user B's first `.identify()` call. 

Does this make sense?

**Comment by arnaudlimbourg** [comment]
@hankim813 oh, right! it does and I am sorry I missed that! I'll try this :)

**Comment by hankim813** [comment]
@arnaudlimbourg yep! Let me know if that works :) I'll close this issue for now!
